### ISSUE TITLE
How to set a fixed width for a table?

### ISSUE THREAD

**Issue by useful-friend** [KDAB/KDReports#17]
I want to divide the width of the page into three parts and put an element in each one.
I decided to use `TableElement` but I could not figure out how to have a fixed width.
could you please point me the right direction to set a fixed width in a table or use another element to solve my problem?
thanks in advance.

**Comment by dfaure-kdab** [comment]
You can set the table itself to have a fixed width by using KDReportsAbstractTableElement::setWidth.

For the columns themselves, excellent timing, I implemented this a few days ago, I just didn't push the commit yet. Pushed right now in commit f543aa5. Can you give it a try and report back?

**Comment by useful-friend** [comment]
Hello there.
I just tested the update you provided and I should say that it fixed the problem well.
Thanks for that.
