### ISSUE TITLE
Qt deprecation warnings

### ISSUE THREAD

**Issue by dismine** [KDAB/KDReports#20]
Hi,

I use your library in my project and since Qt 5.15 I start getting deprecation warnings. Do you have plans to start preparations for future release Qt 6?

**Comment by winterz** [comment]
No immediate plans. I'm sure we'll port to Qt6.  We don't have a timeframe yet.

**Comment by dfaure-kdab** [comment]
We will gladly review patches that fix depreciation warnings, however it can be tricky to keep compatibility with older Qt 5.x versions.

**Comment by correa** [comment]
I have fixed most of them but doing so I found out that Qt's proposed `QXmlStreamReader` argument to `QDomDocument::setContent` instead of `QXmlInputSource` and `QXmlSimpleReader` (guess they are deprecating those) doesn't have a way to enable report-whitespace-only-CharData.

This leads to a unit test failure:
FAIL!  : KDReports::Test::testTextId() Compared values are not the same
   Actual   (report.doc().contentDocument().toPlainText()): "Title.\ntextid.xml\n\n"
   Expected (QString("Title .\ntextid.xml\n\n"))          : "Title .\ntextid.xml\n\n"

**Comment by dfaure-kdab** [comment]
This sounds like something that should be submitted to the Qt bug tracker (as a missing feature, at least)...

On the other hand the use case for `<text inline="true"> </text>` is probably too corner-case to be worried about, this was a unittest I wrote that way for no particular reason that I can remember. I'll accept a change that removes that whitespace-only element from textid.xml

**Comment by correa** [comment]
Just did a little grep and found that almost all of my reports depend on that feature. In the footer we have 
```
    <text alignment="right">Page </text>
    <variable type="pagenumber"/>
    <text inline="true"> of </text>
    <variable type="pagecount"/>
```

**Comment by dfaure-kdab** [comment]
That's not whitespace only like `<text inline="true"> </text>` would be.
IIRC report-whitespace-only-CharData is about char data that is *only* whitespace.
Your elements with " of " should still work fine. Let me know if I'm wrong after updating KDReports :)

**Comment by correa** [comment]
You are right, my tests indicate that the above snippet works even with `QXmlStreamReader`'s lack of report-whitespace-only-CharData. I will run more tests before submitting, but it is basically
```
bool KDReports::Report::loadFromXML( QIODevice* iodevice, ErrorDetails* details )
{
    QDomDocument doc;
    // Read document from the QIODevice, check for errors

    // We need to be able to see the space in <text> </text>, this is why
    // we activate the "report-whitespace-only-CharData" feature.
    // Unfortunately this leads to lots of whitespace text nodes in between real
    // elements in the rest of the document, watch out for that.
    if (iodevice->isOpen())
        iodevice->reset(); //need to do that to allow consecutive calls of loadFromXML()
    else
        iodevice->open(QIODevice::ReadOnly);

    QXmlStreamReader reader( iodevice );
    reader.setNamespaceProcessing( true );

    QString errorMsg;
    int errorLine = 0, errorColumn = 0;
    bool ret = doc.setContent( &reader, true, &errorMsg, &errorLine, &errorColumn );
    if( !ret ) {
        if ( details ) {
            details->setLine( errorLine );
            details->setColumn( errorColumn );
            details->setDriverMessage( errorMsg );
        }
        else
            qWarning( "Malformed XML read in KDReports::Report::loadFromXML(): error message = %s, error line = %d, error column = %d", qPrintable( errorMsg ), errorLine, errorColumn );
        return false;
    }
    return loadFromXML( doc, details );
}
```
but wrapped inside a `QT_VERSION_CHECK(5, 15, 0)`.

**Comment by dfaure-kdab** [comment]
You can remove the old comment about a feature we can't enable anymore :)

**Comment by dfaure-kdab** [comment]
This is all fixed by now, as part of the port to Qt6.
