### ISSUE TITLE
crashed when call showMaximized() in constructor

### ISSUE THREAD

**Issue by CMLDMR** [KDAB/KDReports#39]
everything going well until the call showMaximized(), and then crashed. 

affected version 2.2.0

**Comment by dfaure-kdab** [comment]
Can you give much more detail?
- Which executable? (did you try one of the KDReports examples?)
- Which OS? which compiler?
- How was KDReports built? (cmake options, which IDE)
- What's the backtrace of the crash?

**Comment by CMLDMR** [comment]
- it is my custom application
- windows 11 , msvc 14.34, Qt 6.3.1
- QtCreator IDE and default cmake options
- callgrind result is:
       
![image](https://user-images.githubusercontent.com/10967609/212306503-4e4176dc-4b9c-4ad4-8238-0a67040c203c.png)

**Comment by dfaure-kdab** [comment]
Please rebuild both your application and KDReports in debug mode.

**Comment by CMLDMR** [comment]
this is default rebuild cmake options with Qt6 enabled, rest options is default cmake:


Running C:\Qt\Tools\CMake_64\bin\cmake.exe -S H:/C/KDReports/kdreports-2.2.0 -B H:/C/KDReports/build-kdreports-2.2.0-Desktop_Qt_6_3_1_MSVC2022_64bit-Debug in H:\C\KDReports\build-kdreports-2.2.0-Desktop_Qt_6_3_1_MSVC2022_64bit-Debug.
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE  
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Found WrapVulkanHeaders: C:/VulkanSDK/1.3.224.1/Include  
-- Could NOT find KDChart-qt6 (missing: KDChart-qt6_DIR)
-- Building KDReports 2.2.0 in Debug mode. Installing to C:/Program Files (x86)/KDReports
-- KDChart not found.  skipping the ChartXML example
-- The following OPTIONAL packages have been found:

 * Qt6Core (required version >= 6.0.0)
 * Qt6WidgetsTools (required version >= 6.3.1)
 * Vulkan
 * WrapVulkanHeaders
 * Qt6GuiTools (required version >= 6.3.1)
 * Qt6Widgets (required version >= 6.0.0)
 * Qt6PrintSupport (required version >= 6.0.0)
 * Qt6Xml (required version >= 6.0.0)
 * Qt6CoreTools
 * Qt6Sql

-- The following REQUIRED packages have been found:

 * Qt6Test

-- The following OPTIONAL packages have not been found:

 * KDChart-qt6

-- Configuring done
-- Generating done
-- Build files have been written to: H:/C/KDReports/build-kdreports-2.2.0-Desktop_Qt_6_3_1_MSVC2022_64bit-Debug
Elapsed time: 00:02.


![image](https://user-images.githubusercontent.com/10967609/212308267-8398a495-2d6c-45fe-b1f1-1e1c0f0e4d36.png)

**Comment by dfaure-kdab** [comment]
This isn't a backtrace. The first screenshot, but in debug mode, is what we need.

**Comment by CMLDMR** [comment]
Yes Created.
![image](https://user-images.githubusercontent.com/10967609/212324181-aad67d80-934d-41c8-be9f-18f6602ecb3c.png)

**Comment by CMLDMR** [comment]
how can I see qFatal in QWidget, is it step by step in debug mode?

**Comment by dfaure-kdab** [comment]
"Application Output" tab, no?

**Comment by dfaure-kdab** [comment]
This is clearly not a KDReports problem.

For me to help further, I would have to indeed debug into your application, which isn't something I can do for free.

Please contact info@kdab.com to get a consulting offer.
