### ISSUE TITLE
Tablecell border with can not set 1px

### ISSUE THREAD

**Issue by CMLDMR** [KDAB/KDReports#40]
before I used to 1.9 version and I can make cell border too close to 1px but now I can't.

1.9.0 with tableElement.setBorder (.25);
![image](https://user-images.githubusercontent.com/10967609/212309672-f7d92437-2362-44ba-8f91-5c00eaa71930.png)

2.2.0 with tableElement.setBorder (.25);
![image](https://user-images.githubusercontent.com/10967609/212310054-925525cc-be8f-43d2-bbdb-23f7335bba40.png)

2.2.0 with tableElement.setBorder (1);
![image](https://user-images.githubusercontent.com/10967609/212310300-10aba4ee-c578-46fb-9e86-6712009bdd5e.png)

**Comment by CMLDMR** [comment]
there is no available value between 0 and 1. before i can set 0.25 at version 1.9.0

**Comment by dfaure-kdab** [comment]
KDReports hasn't changed in this area (as far as I recall), this must be a difference between Qt5 and Qt6.
