### ISSUE TITLE
watermark image

### ISSUE THREAD

**Issue by dietmarczekay** [KDAB/KDReports#42]
am I right, the watermark image is a little bit blurred out?
Is there a chance to have the original picture as watermark. I have to  print a diploma and so the "background" image should be as sharp as possible.

Thanks

**Comment by dfaure-kdab** [comment]
You're right, it is indeed quite blurry. I'll look into fixing it.

**Comment by dfaure-kdab** [comment]
Ah, it looks like it's not that. The preview is ok, the PDF output is not.

**Comment by dietmarczekay** [comment]
Thanks for the fast fix. Works.

Just the export to pdf.. is it possible to adjust the quality? It seems, the picture in the pdf file has a bad qualitiy. Thats why the line got a gray "corona" (first image is a screenshot from previewer, second from the saved pdf file)

Dietmar
![Screenshot preview](https://user-images.githubusercontent.com/20709751/232018657-fb2e969a-805b-41c7-bf90-c567dde81658.png)
![Screenshot pdf-viewer](https://user-images.githubusercontent.com/20709751/232018686-f891344a-10ac-480e-b1f9-669dc36fa67a.png)

**Comment by dfaure-kdab** [comment]
I just call QPainter::drawImage, I'm not sure what else we can do, apart from providing a higher-resolution image in the first place.
