### ISSUE TITLE
Can I use KDReports in an open-source application? 

### ISSUE THREAD

**Issue by AhmedAredah** [KDAB/KDReports#43]
Can I use KDReports in an open-source application? I know you changed the license to MIT but your website says "Download Trial". I am making sure that I can use it.
thanks.

**Comment by dfaure-kdab** [comment]
It's indeed MIT, you can certainly use it in an opensource application.
Can you point me to the actual webpage where you saw "Download Trial"? I can't see that on https://www.kdab.com/development-resources/qt-tools/kd-reports/ nor https://github.com/KDAB/KDReports

**Comment by AhmedAredah** [comment]
thank you. 

here is the link: https://www.kdab.com/development-resources/qt-tools/kd-reports/
I am also attaching a picture below
![image](https://github.com/KDAB/KDReports/assets/77444744/77f73587-bf94-4b07-9ede-ee34e4e1b216)

**Comment by dfaure-kdab** [comment]
Oh, thanks. I used the search text (Ctrl+F) feature and didn't find the word trial... because it's part of an image ;-)
Reported to the web team.
