### ISSUE TITLE
KDReport 2.2.1 and Qt 6.7.0

### ISSUE THREAD

**Issue by dietmarczekay** [KDAB/KDReports#56]
Hi,
until installing Qt's 6.7.0, I was able to print and preview any report. Now the program hangs in exporttoFile or creationg a preview with the report as a parameter

Dietmar

**Comment by dfaure-kdab** [comment]
Ouch, indeed, running ReferenceReport I see that `KDReports::Header::preparePaintingPage()` loops forever.
I'll debug it tomorrow.

**Comment by dietmarczekay** [comment]
Thank you! the report component does a great job

**Comment by dietmarczekay** [comment]
file         KDReports/cmake/ECM/modules/ECMQueryQt.cmake contains in line 67 
`set(_cli_option "--query")`
but it should be
`set(_cli_option "-query")` just one minus
