### ISSUE TITLE
PreviewWidget rendering ugly(blurry) on Windows 11 and Qt 6.7 - fix included

### ISSUE THREAD

**Issue by derreisende77** [KDAB/KDReports#58]
First of all, thank you very much for this easy to use library - it really saved my day!
I am using a `PreviewDialog` in my Qt6 app to display the rendered report. I found that on my Windows 11 laptop (1920x1080 resolution, 125% scaling) the rendered content looked really blurry:
![preview_bad_laptop](https://github.com/KDAB/KDReports/assets/8466092/a8adbd3e-bd48-4354-8d9e-d2c252e4f1c5)

After some research I figured that the used `QImage` and `QPixmap` do not automatically take the device scaling into account. I modified `void KDReports::PreviewWidgetPrivate::paintItem(QListWidgetItem *item, int index) const` and `QPixmap KDReports::PreviewWidgetPrivate::paintPreview(int index) const` to fix the rendering and now it looks like this:
![preview_final_really_good](https://github.com/KDAB/KDReports/assets/8466092/f0e700fd-1b32-49d9-a2df-2056ce71e1dd)

I tested the modification solely on Windows 11, both on the laptop screen and an external 4K screen with positive outcome.

I haven't found any info here on how to contribute to this project therefore I am just posting here the modified two functions in the hope you will integrate them in the future - the modifications aren't worth any contribution agreement:
```c++
void KDReports::PreviewWidgetPrivate::paintItem(QListWidgetItem *item, int index) const
{
    // qDebug() << "paintItem" << index;

    // Use a QImage so that the raster paint engine is used.
    // Gives a 7.7 times speedup (!) compared to X11.
    const qreal dpr = q->devicePixelRatioF();
    QImage img(PreviewSize*dpr, PreviewSize*dpr, QImage::Format_ARGB32_Premultiplied);
    img.setDevicePixelRatio(dpr);
    const QSizeF paperSize = m_report->paperSize();
    const qreal paperWidth = paperSize.width() * dpr;
    const qreal paperHeight = paperSize.height() * dpr;
    const qreal longestSide = qMax(paperWidth, paperHeight);
    const qreal width = img.width() * paperWidth / longestSide;
    const qreal height = img.height() * paperHeight / longestSide;
    // img.fill( QColor( Qt::white ).rgb() );
    img.fill(Qt::transparent);
    QPainter painter(&img);
    painter.setRenderHints(QPainter::Antialiasing | QPainter::TextAntialiasing | QPainter::SmoothPixmapTransform, true);
    painter.translate((img.width() - width) / 2, (img.height() - height) / 2);
    painter.fillRect(QRectF(0, 0, width/dpr, height/dpr), QBrush(Qt::white));
    painter.scale(img.width() / longestSide, img.height() / longestSide);
    m_report->paintPage(index, painter);
    painter.setPen(QPen(1));
    painter.drawRect(QRectF(0, 0, paperWidth, paperHeight));

    item->setIcon(QIcon(QPixmap::fromImage(img)));
}

QPixmap KDReports::PreviewWidgetPrivate::paintPreview(int index) const
{
    const QSizeF paperSize = m_report->paperSize();
    const int width = qCeil(paperSize.width() * m_zoomFactor);
    const int height = qCeil(paperSize.height() * m_zoomFactor);
    const qreal dpr = q->devicePixelRatioF();

    QPixmap pixmap(width*dpr, height*dpr);
    pixmap.setDevicePixelRatio(dpr);
    pixmap.fill(Qt::transparent);
    // qDebug() << width << "," << height;

    // qDebug() << "paintPreview " << index;

    QPainter painter(&pixmap);
    painter.setRenderHints(QPainter::Antialiasing | QPainter::TextAntialiasing | QPainter::SmoothPixmapTransform, true);
    
    painter.fillRect(QRectF(0, 0, width, height), QBrush(Qt::white));
    painter.scale(m_zoomFactor, m_zoomFactor);
    m_report->paintPage(index, painter);
    painter.setPen(QPen(1));
    painter.drawRect(QRectF(0, 0, paperSize.width(), paperSize.height()));

    return pixmap;
}

```

**Comment by derreisende77** [comment]
I introduced a bug in the thumbnail list where the image was incorrectly scaled. This is visible in my screenshots :( 
I fixed the posted `paintItem` method and the scaling *should* be correct now.

**Comment by dfaure-kdab** [comment]
Thanks for the fix!

Just one minor issue: isn't the `painter.drawRect(QRectF(0, 0, paperWidth, paperHeight));` in `paintItem`
incorrect because those values have been multiplied by dpr, (and the painter isn't scaled down)? Only `img` knows about the `dpr`, QPainter doesn't.

**Comment by derreisende77** [comment]
@dfaure-kdab Yes you are right, it must be `painter.drawRect(QRectF(0, 0, paperWidth/dpr, paperHeight/dpr));`
Just checked and now it has the border drawn correctly.

**Comment by dfaure-kdab** [comment]
I simplified the code a bit to avoid multiplying and dividing by dpr in so many places.

Many thanks for the report and first version of the fix!
