### ISSUE TITLE
using the reoprt in Qt6

### ISSUE THREAD

**Issue by dietmarczekay** [KDAB/KDReports#68]
I have always to adjust the cmake config files to
```
include(CMakeFindDependencyMacro)

find_dependency(Qt6Core 6.0.0)
find_dependency(Qt6Widgets 6.0.0)
find_dependency(Qt6PrintSupport 6.0.0)
find_dependency(Qt6Xml 6.0.0)

if (1)
    find_dependency(KDChart-qt6)
endif()
```
the original one is without the "6" and my qt with cmake did not find QtCore for example

**Comment by dfaure-kdab** [comment]
Thanks for the report! Fixed.

**Comment by dietmarczekay** [comment]
Please reopen the issue:

expected in KDReports-qt6Config.cmake:
####################################################################################

include(CMakeFindDependencyMacro)

find_dependency(Qt6Core 6.0.0)
find_dependency(Qt6Widgets 6.0.0)
find_dependency(Qt6PrintSupport 6.0.0)
find_dependency(Qt6Xml 6.0.0)

if (1)
    find_dependency(KDChart-qt6)
endif()

but actual:

####################################################################################

include(CMakeFindDependencyMacro)

find_dependency(QtCore 6.0.0)
find_dependency(QtWidgets 6.0.0)
find_dependency(QtPrintSupport 6.0.0)
find_dependency(QtXml 6.0.0)

if (1)
    find_dependency(KDChart)
endif()

I made a git pull before todays build. Configuration was done with cmake-gui, in the first run cmake-gui wants to configure for qt5, then i have the choise and can select qt6. Build and install worked. But then I have to edit the cmake config file to get my project to compile

**Comment by dfaure-kdab** [comment]
I wonder if you generating files for Qt5 first, and then for Qt6, means the Config file doesn't get regenerated.
If you just delete KDReports-qt6Config.cmake and re-run cmake, is the file generated correctly?

**Comment by dietmarczekay** [comment]
after deleting, the file is regenerated correctly. My point is, if cmake-gui is used, the option "KDReports_QT6" is first checkable after first run. So it seems to be a comfort thing. Using cmake with the right command line syntax and running for QT6 prevent the problem

**Comment by dfaure-kdab** [comment]
https://github.com/KDAB/KDReports/pull/75 should fix that

**Comment by dietmarczekay** [comment]
Many thanks!
