### ISSUE TITLE
Library doesn't build with Qt 5.7

### ISSUE THREAD

**Issue by larsivi** [KDAB/KDReports#8]
Maybe I'm missing something, but I'm trying to build KDReports (together with our project), against Qt 5.7 and this fails (on Kubuntu 16.04).

Qt 5.7 mandates C++11, but g++.pri adds -ansi. These are not compatible C++ flags, and so the compilation fails once it enters the Qt headers.

I don't see a non-intrusive way to fix this on my side.

**Comment by winterz** [comment]
try this:
In toplevel g++.pri you'll see a variable called NORMAL_CFLAGS set to -Wno-long-long -ansi
remove the -ansi from that, so you should have NORMAL_CFLAGS = -Wno-long-long

**Comment by larsivi** [comment]
Yes, I tried that and it worked, but it wasn't non-intrusive :)

**Comment by winterz** [comment]
committed the fix for g++.pri in 3100fba9c3f1e310383a11fcba679deae82898a0
