### ISSUE TITLE
qmake produce error

### ISSUE THREAD

**Issue by jack-gms** [KDAB/KDReports#9]
qmake produce error (both on linux and win): 
Cannot find file: /myprojects/KDReports-kdreports-1.7.1/include/include.pro

-> In kdreports.pro, line 2, there is the word "include" appearing in SUBDIRS.
Removing it make qmake works.

**Comment by dfaure-kdab** [comment]
The include directory is generated. You need to run autogen.py before running qmake, see INSTALL.txt
